### ISSUE TITLE
Parsing error

### ISSUE THREAD

**Issue by GoogleCodeExporter** [gdsaxton/python-nameparser#20]
```
What steps will reproduce the problem?

1. from nameparser import HumanName
2. name = HumanName("Ramesh Vel")

What is the expected output? What do you see instead?

Expected: nothing
Currently: 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build\bdist.win32\egg\nameparser\parser.py", line 49, in __init__
  File "build\bdist.win32\egg\nameparser\parser.py", line 179, in full_name
  File "build\bdist.win32\egg\nameparser\parser.py", line 243, in _parse_full_name
  File "build\bdist.win32\egg\nameparser\parser.py", line 215, in _parse_pieces
IndexError: pop index out of range

What version of the product are you using? On what operating system?

nameparser 0.2.0
Python 2.7
Windows 7

Please provide any additional information below.
```

Original issue reported on code.google.com by `vasile...@gmail.com` on 6 Jul 2012 at 8:24

**Comment by GoogleCodeExporter** [comment]
```
I cannot reproduce this on the latest version 0.2.2 so I'm going to call it 
fixed. Let me know if you still see parser crashes.
```

Original comment by `dere...@gmail.com` on 7 Oct 2012 at 10:42
- Changed state: **Fixed**
