### ISSUE TITLE
Parser crash on "Wu Di"

### ISSUE THREAD

**Issue by GoogleCodeExporter** [gdsaxton/python-nameparser#25]
```
What steps will reproduce the problem?
>>> nameparser.parser.HumanName("Wu Di")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/silver/env/titan/local/lib/python2.7/site-packages/nameparser-0.2.0-py2.7.egg/nameparser/parser.py", line 49, in __init__
    self.full_name = full_name
  File "/home/silver/env/titan/local/lib/python2.7/site-packages/nameparser-0.2.0-py2.7.egg/nameparser/parser.py", line 179, in full_name
    self._parse_full_name()
  File "/home/silver/env/titan/local/lib/python2.7/site-packages/nameparser-0.2.0-py2.7.egg/nameparser/parser.py", line 243, in _parse_full_name
    pieces = self._parse_pieces(parts)
  File "/home/silver/env/titan/local/lib/python2.7/site-packages/nameparser-0.2.0-py2.7.egg/nameparser/parser.py", line 215, in _parse_pieces
    pieces.pop(i+1)
IndexError: pop index out of range


What version of the product are you using? On what operating system?
nameparser 0.2.0 installed from PyPi, python 2.7.3 x64


```

Original issue reported on code.google.com by `alexey.s...@muranosoft.com` on 17 Sep 2012 at 7:14

**Comment by GoogleCodeExporter** [comment]
```
I can't reproduce this on the latest version (0.2.2). I think maybe it was 
fixed. Let me know if it's still an issue.
```

Original comment by `dere...@gmail.com` on 7 Oct 2012 at 10:29

**Comment by GoogleCodeExporter** [comment]
Original comment by `dere...@gmail.com` on 7 Oct 2012 at 10:54
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
Yeah, it works in latest versions, thanks!
```

Original comment by `alexey.s...@muranosoft.com` on 8 Oct 2012 at 10:41
