### ISSUE TITLE
Multiple articles cause a crash

### ISSUE THREAD

**Issue by GoogleCodeExporter** [gdsaxton/python-nameparser#28]
```
This is with version 0.2.5.

HumanName('Last of the Mohicans')

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "python2.7.3/lib/python2.7/site-packages/nameparser/parser.py", line 57, in __init__
    self.full_name = full_name
  File "python2.7.3/lib/python2.7/site-packages/nameparser/parser.py", line 202, in full_name
    self._parse_full_name()
  File "python2.7.3/lib/python2.7/site-packages/nameparser/parser.py", line 284, in _parse_full_name
    pieces = self._parse_pieces(parts)
  File "python2.7.3/lib/python2.7/site-packages/nameparser/parser.py", line 228, in _parse_pieces
    i = pieces.index(conj)
ValueError: u'the' is not in list

```

Original issue reported on code.google.com by `jayqhac...@gmail.com` on 12 Feb 2013 at 10:49

**Comment by GoogleCodeExporter** [comment]
```
Thanks for reporting. I released a new version tonight that fixes that. give 
0.2.7 a try. I put a try around that index call so instead of barfing it will 
just make some wrong decisions.
```

Original comment by `dere...@gmail.com` on 14 Feb 2013 at 4:47
- Changed state: **Fixed**
